### ISSUE TITLE
simple-compress doesn't support node v10.15.0

### ISSUE THREAD

**Issue by xsandeep** [i-e-b/SimpleCompress#9]
Hi,

Tried using node v10.15.0, figured out the upper versions of node, I think (v6.9.4 +) have support for simple-compress.
The npm gets installed, but we cannot access the 'sz' command after that.

**Comment by i-e-b** [comment]
Hi. Some questions:

* Did you use `npm i -g`?
* Do you have any error messages?
* Do you use simple-compress as a library, and if so, it that working?

**Comment by i-e-b** [comment]
Closing until further information provided

**Comment by xsandeep** [comment]
I was caught up in some other tasks.
So the issue is - If I'm working with the latest node versions, I am caught up in an issue like.
**`inp.end is not a function`**

![image](https://user-images.githubusercontent.com/30051235/71663570-c35b7680-2d7b-11ea-9bca-c57d25b70bbb.png)

> I have not checked with Linux, this issue might only be with the Windows environment.
